# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define :oai5gcn do |oai5gcn|
    oai5gcn.vm.hostname = "oai-5g-cn"
    oai5gcn.vm.network "private_network", ip: "192.168.2.10"
  end
end
